travis:
  secure:
    BINSTAR_TOKEN: BM6IoKe6JY+6bxE+XhSs57aH8yEdXpel2CPG7oehJGdH2pz1MVbu6FKl506rwwiyqoQ1UKYR4Ukwmc9H/dlFiFK/U86NB4rrdk/A5hQa9Trl3ksy9lMetpbY3JKEm9FNf+O2JLLkNDTdB4B2uN8kRK0RvslRCX0YmhDgT8FCU/Hn1Yhx3gtf/puU2p06mM4FFclbnUiNHmfwf0Yd1lHGMHz/ceTuX5OYhKO5UWdPzrEDtD0Ql5lpSKs+gcCohkRXmMTIAQONyMmfr+bK09fp9GzwZaMEugVul7Mgr1JpGKLiutaG6jah+s02PWt2br+wuSRejmdrV/3YrYxvBVPH8mKE1Y/pGEXzF/6nYLzHXZ4NK1vsxourkQ9oUiBLQh0e1PpSRdSvT6dGwWPNPUVW3Qme0XMdEKMvjTyd2UIMMEy8voDRHIQxrojVUlIhrP/+JoT+vMCn9qP/yR6Z4c8hALEiJwnNI8PX1fvMnppC5nFlO2HL6nWQOpJD89ZuRU3IkhsyXCI9ljeOtL9rh5xQRUPtyIRdIBPUg0zRdEnYqcy46GgM3acpVSCyqucZNptYVE9/VI1q3jdBD5jl5AVhtDxYuIBCuI6F23s2lM9QI0mnWPQT4Tl09Uv79xW19ztjRY46eaA7iJRAFbIT+4QOxwn1+rYcMcd2j3lAk3sGV8w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
