travis:
  secure:
    BINSTAR_TOKEN: etc8PcnpB70wFmKeIMrixG8pVAkaKj7TfJigcytmFK5ReTyOx/QBBd/oydRPXzDceXjQpILb5c1a/8XerkWJFcm9ISLBrU6dNIedaFdejd6mGgs/nOh03F8euwJHKfAtXi9ige/sJ6+Ivt/xzcAMPrtSE3Pu5EhUdeh8cKM1g2KctPpD9rFQ7RneIstIdMc14g034L1YyuP+Fhm52J79ks6tbjhgRgu0sQZhve39x1UMfrGjbOhajFoEsD+IPCfUeKjn1xvCnAWjfXZSSR2r773lla8Z9TH7ml1b2OztP+ZlSCLwpPWJ3dGlty8nwFFjNK4/3snMlK+Z5m0XJd8vdGI5Dcf4MrfBM1TCms2wEIWOcC0lQ5SoNpvj1PNv/90S7KDfYA0lSh+Knq2oXy8vI1bBOjAIDvr3tn0nqPjiNXl6qXOPWB1qltT6R71PLjNxmSvNPnEeJ9cLpJkuyuD8C3/FQTA3dsymWrR5hl7/ISiRww2HNAUNwIcZtgod9RltRiRE2Bx2vPUKg8JW1T+n9P8zU6T+u88QEZI4bByXcKAc55sOi01QbdpKFmSVgfwR198pOQeJrbncvzO73ChU40BBlDRfL6jk8utGT+5t4EIMKGkieP9ZeQ6dT11gkSZ6AkewGx41Uw2BUVpqt4jnBGl/in5Js7DhB38tuUQN0VE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
